#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "main" ]; then
  echo ">>> No committing to main! <<<"
  exit 1
fi

make lint || exit 1
make test || exit 1
